# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Open Data in Experimental Mechanics
email: contact@openexpmechanics.science
description: > # this means to ignore newlines until "baseurl:"
   Open Data in Experimental Mechanics
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://opendataexpmechanics.github.io/" # the base hostname & protocol for your site
twitter_username: OpenDataExpMech
github_username:  OpenDataExpMechanics 

# Build settings
markdown: kramdown
kramdown:
  input: GFM

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
