# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Open Data in Experimental Mechanics
email: contact@openexpmechanics.science
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://opendataexpmechanics.github.io" # the base hostname & protocol for your site

#sidebar
default-image: webjeda-logo-big.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: webjeda
copyright:
   name: OpenDataExpMechanics
   link: https://opendataexpmechanics.github.io

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics:

# Comments
disqus-shortname:

#social
twitter: http://twitter.com/@OpenDataExpMech
github: http://github.com/OpenDataExpMechanics

#facebook like box
#fb-app-id: 549480635219583
#fb-page-url: https://www.facebook.com/webjeda/
#fb-page-title: webjeda

# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag]
